#!/bin/bash

PATH1="/usr/src/linux-2.4.18-14custom/"
echo $PATH1  
cp "$PATH1"include/linux/list.h .
cp "$PATH1"include/linux/sched.h .
cp "$PATH1"include/asm-i386/errno.h .
cp "$PATH1"kernel/exit.c .
cp "$PATH1"kernel/fork.c .
