#!/bin/bash

cd /usr/src/linux-2.4.18-14custom
make -f Makefile bzImage
if [ "$1" == "-full" ] || [ "$2" == "-full" ]; then
  make -f Makefile modules
  make -f Makefile modules_install
fi
make -f Makefile install
cd /boot
mkinitrd -f 2.4.18-14custom.image 2.4.18-14custom
if [ "$1" == "-reboot" ] || [ "$2" == "-reboot" ]; then
  reboot
fi
